##===- lld/lib/ReaderWriter/Makefile ---------------------------*- Makefile -*-===##
#
#                     The LLVM Compiler Infrastructure
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
#
##===----------------------------------------------------------------------===##

LLD_LEVEL := ../..
LIBRARYNAME := lldReaderWriter

# these link against this lib
PARALLEL_DIRS := ELF MachO PECOFF YAML

include $(LLD_LEVEL)/Makefile
